import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
          <title>Wallstreet finds</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar/>
        <Component {...pageProps} />
      </div>
    </>
  )
}
